import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./Components/Menu/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className=" flex bg-slate-200 w-full h-full p-8 ">
          <Menu></Menu>
        </div>
      </body>
    </html>
  );
}
