import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./Components/Menu/Menu";
import Navbar from "./Components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className=" flex  gap-10 bg-slate-100  p-8 ">
          <div>
            <Menu></Menu>
          </div>
          <div className=" w-full space-y-7">
              <Navbar></Navbar>
              {children}
          </div>
        </div>
      </body>
    </html>
  );
}
